.\" Man page for kyliln-screenshot
.TH KYLINSCREENSHOT 1 "19 August 2020" "UKUI Desktop Environment"
.\" Please adjust this date when revising the manpage.
.\"
.SH "NAME"
kylin-screenshot \- The tool for the UKUI Desktop Environment
.SH "SYNOPSIS"
.B kylin-screenshot
.SH "DESCRIPTION"
The \fBkylin-screenshot\fR program is a part of the ukui-menu, powerful yet simple-to-use screenshot software.
.PP
This manual page documents the \fBkylin-screenshot\fR command.
.P
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
https://github.com/ubuntukylin/kylin-screenshot/issues
.SH "AUTHORS"
.SS This Man Page has been written for the UKUI Desktop Environment by:
huanhuan zhang <zhanghuanhuan@kylinos.cn> (2020)
.SH "SEE ALSO"
