name: Check build

on:
  push:
    branches:
      - master
    
  pull_request:
    branches:
      - master

  schedule:
    - cron: '0 0 * * *'

jobs:
  archlinux-latest:
    name: on Archlinux Latest
    runs-on: ubuntu-20.04
    container: docker.io/library/archlinux:latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Refresh Pacman repository
        run: pacman -Sy
      - name: Install basic dependencies
        run: pacman -S --noconfirm base-devel cmake pkgconf
      - name: Install latest basic Qt5 in repository
        run: pacman -S --noconfirm qt5-base qt5-tools
      - name: Install project denpendencies
        run: pacman -S --noconfirm qt5-svg ffmpeg libpulse qt5-x11extras libxfixes libx11 libxinerama glibc
      - name: QMake configure & Make
        run: |
          qmake-qt5 .;
          make -j$(nproc);
        
  ubuntu-focal:
    name: on Ubuntu Focal
    runs-on: ubuntu-20.04
    container: docker.io/library/ubuntu:focal
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Update APT repository
        run:  apt-get update -y
      - name: Install basic dependencies
        env:
          DEBIAN_FRONTEND: noninteractive            
        run: apt-get -y install build-essential pkg-kde-tools pkg-config cmake
      - name: Install latest basic Qt5 in repository
        env:
          DEBIAN_FRONTEND: noninteractive
        run: apt-get -y install qt5-default qttools5-dev-tools qt5-qmake qtbase5-dev qtbase5-private-dev
      - name: Install project denpendencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: apt-get -y install libqt5svg5-dev libavformat-dev libavcodec-dev libavutil-dev libswscale-dev libpulse-dev libqt5x11extras5 libqt5x11extras5-dev libxfixes3 libxfixes-dev libx11-dev libxinerama1 libxinerama-dev
      - name: QMake configure & Make
        run: |
          qmake .;
          make -j$(nproc);

  ubuntu-devel:
    name: on Ubuntu Devel
    runs-on: ubuntu-20.04
    container: docker.io/library/ubuntu:devel
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Update APT repository
        run:  apt-get update -y
      - name: Install basic dependencies
        env:
          DEBIAN_FRONTEND: noninteractive            
        run: apt-get -y install build-essential pkg-kde-tools pkg-config cmake
      - name: Install latest basic Qt5 in repository
        env:
          DEBIAN_FRONTEND: noninteractive
        run: apt-get -y install qt5-default qttools5-dev-tools qt5-qmake qtbase5-dev qtbase5-private-dev
      - name: Install project denpendencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: apt-get -y install libqt5svg5-dev libavformat-dev libavcodec-dev libavutil-dev libswscale-dev libpulse-dev libqt5x11extras5 libqt5x11extras5-dev libxfixes3 libxfixes-dev libx11-dev libxinerama1 libxinerama-dev
      - name: QMake configure & Make
        run: |
          qmake .;
          make -j$(nproc);

  ubuntu-latest:
    name: on Ubuntu Latest
    runs-on: ubuntu-20.04
    container: docker.io/library/ubuntu:latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Update APT repository
        run:  apt-get update -y
      - name: Install basic dependencies
        env:
          DEBIAN_FRONTEND: noninteractive            
        run: apt-get -y install build-essential pkg-kde-tools pkg-config cmake
      - name: Install latest basic Qt5 in repository
        env:
          DEBIAN_FRONTEND: noninteractive
        run: apt-get -y install qt5-default qttools5-dev-tools qt5-qmake qtbase5-dev qtbase5-private-dev
      - name: Install project denpendencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: apt-get -y install libqt5svg5-dev libavformat-dev libavcodec-dev libavutil-dev libswscale-dev libpulse-dev libqt5x11extras5 libqt5x11extras5-dev libxfixes3 libxfixes-dev libx11-dev libxinerama1 libxinerama-dev
      - name: QMake configure & Make
        run: |
          qmake .;
          make -j$(nproc);
