name: Check build

on:
  push:
    branches:
      - master
    
  pull_request:
    branches:
      - master

  schedule:
    - cron: '0 0 * * *'

jobs:
  ubuntu-focal:
    name: on Ubuntu Focal
    runs-on: ubuntu-20.04
    container: docker.io/library/ubuntu:focal
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Update APT repository
        run:  apt-get update -y
      - name: Install basic dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
          BASIC_PAKCAGES: (
            build-essential
            pkg-kde-tools
            pkg-config
            cmake
          )
        run: apt-get -y install ${BASIC_PACKAGES[@]}
      - name: Install latest basic Qt5 in repository
        env:
          DEBIAN_FRONTEND: noninteractive
          QT5_BASIC_PACKAGES: (
            qt5-default
            qttools5-dev-tools
            qt5-qmake
            qtbase5-dev
            qtbase5-private-dev
          )
        run: apt-get -y install ${QT5_BASIC_PACKAGES[@]}
      - name: Install project denpendencies
        env:
          DEBIAN_FRONTEND: noninteractive
          PROJECT_PACKAGES: (
            libqt5svg5-dev
            libavformat-dev
            libavcodec-dev
            libavutil-dev
            libswscale-dev
            libpulse-dev
            libqt5x11extras5
            libqt5x11extras5-dev
            libxfixes3
            libxfixes-dev
            libx11-dev
            libxinerama1
            libxinerama-dev
          )
        run: apt-get -y install ${PROJECT_PACKAGES[@]}
      - name: QMake configure & Make
        run: |
          qmake .;
          make -j$(nproc);

  ubuntu-devel:
    name: on Ubuntu Devel
    runs-on: ubuntu-20.04
    container: docker.io/library/ubuntu:devel
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Update APT repository
        run:  apt-get update -y
      - name: Install basic dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
          BASIC_PAKCAGES: (
            build-essential
            pkg-kde-tools
            pkg-config
            cmake
          )
        run: apt-get -y install ${BASIC_PACKAGES[@]}
      - name: Install latest basic Qt5 in repository
        env:
          DEBIAN_FRONTEND: noninteractive
          QT5_BASIC_PACKAGES: (
            qt5-default
            qttools5-dev-tools
            qt5-qmake
            qtbase5-dev
            qtbase5-private-dev
          )
        run: apt-get -y install ${QT5_BASIC_PACKAGES[@]}
      - name: Install project denpendencies
        env:
          DEBIAN_FRONTEND: noninteractive
          PROJECT_PACKAGES: (
            libqt5svg5-dev
            libavformat-dev
            libavcodec-dev
            libavutil-dev
            libswscale-dev
            libpulse-dev
            libqt5x11extras5
            libqt5x11extras5-dev
            libxfixes3
            libxfixes-dev
            libx11-dev
            libxinerama1
            libxinerama-dev
          )
        run: apt-get -y install ${PROJECT_PACKAGES[@]}
      - name: QMake configure & Make
        run: |
          qmake .;
          make -j$(nproc);

  ubuntu-latest:
    name: on Ubuntu Latest
    runs-on: ubuntu-20.04
    container: docker.io/library/ubuntu:latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Update APT repository
        run:  apt-get update -y
      - name: Install basic dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
          BASIC_PAKCAGES: (
            build-essential
            pkg-kde-tools
            pkg-config
            cmake
          )
        run: apt-get -y install ${BASIC_PACKAGES[@]}
      - name: Install latest basic Qt5 in repository
        env:
          DEBIAN_FRONTEND: noninteractive
          QT5_BASIC_PACKAGES: (
            qt5-default
            qttools5-dev-tools
            qt5-qmake
            qtbase5-dev
            qtbase5-private-dev
          )
        run: apt-get -y install ${QT5_BASIC_PACKAGES[@]}
              
      - name: Install project denpendencies
        env:
          DEBIAN_FRONTEND: noninteractive
          PROJECT_PACKAGES: (
            libqt5svg5-dev
            libavformat-dev
            libavcodec-dev
            libavutil-dev
            libswscale-dev
            libpulse-dev
            libqt5x11extras5
            libqt5x11extras5-dev
            libxfixes3
            libxfixes-dev
            libx11-dev
            libxinerama1
            libxinerama-dev
          )
        run: apt-get -y install ${PROJECT_PACKAGES[@]}
      - name: QMake configure & Make
        run: |
          qmake .;
          make -j$(nproc);
